export const mockVehicles = [
  {
    id: 1,
    image: "/carpix.jpg",
    status: "À vendre",
    brand: "Oxalys",
    model: "Série 4",
    location: "Bordeaux",
    year: 2022,
    km: 32000,
    energy: "GPL",
    price: 15000,
  },
  {
    id: 2,
    image: "/carpix.jpg",
    status: "À vendre",
    brand: "Oxalys",
    model: "Série 4",
    location: "Bordeaux",
    year: 2022,
    km: 32000,
    energy: "GPL",
    price: 15000,
  },
  {
    id: 3,
    image: "/carpix.jpg",
    status: "À vendre",
    brand: "Oxalys",
    model: "Série 4",
    location: "Bordeaux",
    year: 2022,
    km: 32000,
    energy: "GPL",
    price: 15000,
  },
  {
    id: 4,
    image: "/carpix.jpg",
    status: "À vendre",
    brand: "Oxalys",
    model: "Série 4",
    location: "Bordeaux",
    year: 2022,
    km: 32000,
    energy: "GPL",
    price: 15000,
  },
  {
    id: 5,
    image: "/carpix.jpg",
    status: "À vendre",
    brand: "Oxalys",
    model: "Série 4",
    location: "Bordeaux",
    year: 2022,
    km: 32000,
    energy: "GPL",
    price: 15000,
  },
  {
    id: 6,
    image: "/carpix.jpg",
    status: "À vendre",
    brand: "Oxalys",
    model: "Série 4",
    location: "Bordeaux",
    year: 2022,
    km: 532590,
    energy: "GPL",
    price: 15000,
  },
];
