export const mockVehicles = [
  {
    id: 1,
    image: "/carpix.png",
    status: "rental",
    brand: "Oxalys",
    model: "Série 4",
    location: "Bordeaux",
    year: 2022,
    km: 32000,
    energy: "GPL",
    price: 250,
  },
  {
    id: 2,
    image: "/carpix3.png",
    status: "rental",
    brand: "Oxalys",
    model: "Série 4",
    location: "Bordeaux",
    year: 2022,
    km: 32000,
    energy: "GPL",
    price: 150,
  },
  {
    id: 3,
    image: "/carpix.png",
    status: "sale",
    brand: "Oxalys",
    model: "Série 4",
    location: "Bordeaux",
    year: 2022,
    km: 32000,
    energy: "GPL",
    price: 15000,
  },
  {
    id: 4,
    image: "/carpix3.png",
    status: "sale",
    brand: "Oxalys",
    model: "Série 4",
    location: "Bordeaux",
    year: 2022,
    km: 32000,
    energy: "GPL",
    price: 15000,
  },
  {
    id: 5,
    image: "/carpix.png",
    status: "rental",
    brand: "Oxalys",
    model: "Série 4",
    location: "Bordeaux",
    year: 2022,
    km: 32000,
    energy: "GPL",
    price: 150,
  },
  {
    id: 6,
    image: "/carpix3.png",
    status: "rental",
    brand: "Oxalys",
    model: "Série 4",
    location: "Bordeaux",
    year: 2022,
    km: 532590,
    energy: "GPL",
    price: 150,
  },
];
